/**
 * Reji Kontrol Konsolu V1.0 — stil kataloğu.
 * Tüm konsol yüzeyleri tek StyleSheet üzerinden paylaşılır.
 */

import { StyleSheet } from 'react-native';

export const rejiStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#070B14',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    gap: 16,
    maxWidth: 520,
    width: '100%',
    alignSelf: 'center',
  },
  statusSection: {
    alignItems: 'center',
    gap: 10,
  },
  title: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 2.4,
  },
  blackoutBtn: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#7F1D1D',
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.65)',
  },
  blackoutBtnActive: {
    backgroundColor: '#450A0A',
    borderColor: '#F87171',
  },
  blackoutBtnText: {
    color: '#FEE2E2',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
    textAlign: 'center',
  },
  blackoutBanner: {
    width: '100%',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.7)',
    backgroundColor: 'rgba(127, 29, 29, 0.45)',
    padding: 14,
  },
  blackoutBannerTitle: {
    color: '#FECACA',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  blackoutBannerHint: {
    color: '#FCA5A5',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 16,
  },
  blackoutExitBtn: {
    marginTop: 4,
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: '#1F2937',
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.4)',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  blackoutExitBtnText: {
    color: '#FEE2E2',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  stadiumCard: {
    width: '100%',
    gap: 8,
  },
  stadiumHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    flexWrap: 'wrap',
  },
  multiViewToggle: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    backgroundColor: '#10182A',
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  multiViewToggleActive: {
    borderColor: 'rgba(56, 189, 248, 0.55)',
    backgroundColor: 'rgba(14, 116, 144, 0.28)',
  },
  multiViewToggleText: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  multiViewToggleTextActive: {
    color: '#7DD3FC',
  },
  multiViewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  camTile: {
    flexBasis: '47%',
    flexGrow: 1,
    maxWidth: '49%',
    aspectRatio: 1.15,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    backgroundColor: '#080D18',
  },
  camTileStandby: {
    borderColor: 'rgba(148, 163, 184, 0.12)',
  },
  camFeed: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  camOverlay: {
    flex: 1,
    padding: 8,
    justifyContent: 'space-between',
  },
  camLabel: {
    color: '#E2E8F0',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  camTitle: {
    color: '#F8FAFC',
    fontSize: 11,
    fontWeight: '700',
  },
  camSubtitle: {
    color: '#94A3B8',
    fontSize: 9,
    fontWeight: '600',
  },
  camBpm: {
    color: '#6EE7B7',
    fontSize: 10,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  camStandbyBadge: {
    alignSelf: 'flex-start',
    borderRadius: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.45)',
    paddingVertical: 3,
    paddingHorizontal: 6,
  },
  camStandbyText: {
    color: '#FCA5A5',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  stadiumFrame: {
    width: '100%',
    height: 168,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    backgroundColor: '#080D18',
    position: 'relative',
    overflow: 'hidden',
  },
  stadiumFrameBlackout: {
    backgroundColor: '#000000',
    borderColor: 'rgba(248, 113, 113, 0.35)',
  },
  ledBlackout: {
    backgroundColor: '#000000',
    opacity: 1,
    borderColor: 'rgba(248, 113, 113, 0.2)',
  },
  pitch: {
    position: 'absolute',
    top: '34%',
    left: '34%',
    width: '32%',
    height: '32%',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(74, 222, 128, 0.25)',
    backgroundColor: 'rgba(20, 83, 45, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pitchText: {
    color: 'rgba(167, 243, 208, 0.55)',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  ledBlock: {
    position: 'absolute',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  ledTop: {
    top: 8,
    left: '18%',
    right: '18%',
    height: 36,
  },
  ledBottom: {
    bottom: 8,
    left: '18%',
    right: '18%',
    height: 36,
  },
  ledLeft: {
    left: 8,
    top: '28%',
    bottom: '28%',
    width: 44,
  },
  ledRight: {
    right: 8,
    top: '28%',
    bottom: '28%',
    width: 44,
  },
  ledLabel: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '700',
  },
  ledLabelLit: {
    color: '#0B1220',
  },
  signalBox: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: '#10182A',
    borderWidth: 1,
  },
  signalDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  signalText: {
    color: '#F4F6FF',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 26,
  },
  bpmDetail: {
    color: '#38BDF8',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  feedbackText: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  timerPanel: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#0A101C',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
  },
  timerPanelActive: {
    borderColor: 'rgba(251, 191, 36, 0.55)',
    backgroundColor: 'rgba(69, 26, 3, 0.35)',
  },
  timerLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2,
  },
  timerValue: {
    color: '#64748B',
    fontSize: 32,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    letterSpacing: 2,
  },
  timerValueActive: {
    color: '#FBBF24',
  },
  overrideBtn: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#334155',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  overrideBtnResume: {
    backgroundColor: '#166534',
    borderColor: 'rgba(74, 222, 128, 0.45)',
  },
  overrideBtnText: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  block: {
    gap: 8,
  },
  sectionLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.4,
  },
  segmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    backgroundColor: '#0C1220',
    borderRadius: 12,
    padding: 5,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
  },
  segmentBtn: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: 90,
    borderRadius: 9,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  segmentBtnActive: {
    backgroundColor: '#1D4ED8',
  },
  segmentText: {
    color: '#9AA3C2',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 15,
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  scenarioList: {
    gap: 6,
  },
  scenarioCard: {
    backgroundColor: '#10182A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    paddingVertical: 13,
    paddingHorizontal: 12,
  },
  scenarioCardActive: {
    borderColor: 'rgba(56, 189, 248, 0.65)',
    backgroundColor: 'rgba(14, 116, 144, 0.28)',
  },
  scenarioTitle: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  scenarioTitleActive: {
    color: '#7DD3FC',
  },
  actionsSection: {
    gap: 10,
  },
  buttonWrap: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  button: {
    minHeight: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  metricsSection: {
    flexDirection: 'row',
    gap: 10,
  },
  metricPanel: {
    flex: 1,
    backgroundColor: '#10182A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    paddingVertical: 12,
    paddingHorizontal: 10,
    gap: 3,
  },
  metricPanelLiveRed: {
    borderColor: 'rgba(248, 113, 113, 0.55)',
    backgroundColor: 'rgba(127, 29, 29, 0.35)',
  },
  metricPanelLiveGreen: {
    borderColor: 'rgba(52, 211, 153, 0.55)',
    backgroundColor: 'rgba(6, 78, 59, 0.35)',
  },
  metricPanelSync: {
    borderColor: 'rgba(167, 139, 250, 0.45)',
    backgroundColor: 'rgba(76, 29, 149, 0.28)',
  },
  metricLabel: {
    color: '#9AA3C2',
    fontSize: 11,
    fontWeight: '500',
  },
  metricValue: {
    color: '#F4F6FF',
    fontSize: 18,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  metricValueLive: {
    color: '#FCA5A5',
  },
  metricValueLiveGreen: {
    color: '#6EE7B7',
  },
  bpmCard: {
    gap: 8,
    backgroundColor: '#0C1220',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    padding: 10,
  },
  /** V7.0 — Senaryo profil / hafıza paneli */
  presetCard: {
    gap: 10,
    backgroundColor: '#0C1220',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.22)',
    padding: 12,
  },
  presetHint: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  presetSlotRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  presetSlotBtn: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: 96,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10182A',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
  },
  presetSlotBtnActive: {
    backgroundColor: '#0E4A6E',
    borderColor: 'rgba(56, 189, 248, 0.65)',
  },
  presetSlotText: {
    color: '#9AA3C2',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
    textAlign: 'center',
  },
  presetSlotTextActive: {
    color: '#E0F2FE',
  },
  presetActionRow: {
    gap: 6,
  },
  presetExportBtn: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#1E3A5F',
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.45)',
  },
  presetExportBtnText: {
    color: '#E0F2FE',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  presetImportBtn: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  presetImportBtnText: {
    color: '#CBD5E1',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  /** V9.0 — Network config paneli */
  netCard: {
    gap: 8,
    backgroundColor: '#0A101C',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.28)',
    padding: 12,
  },
  netHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  netChevron: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
  },
  netSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  netStatusPill: {
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
  },
  netStatusOk: {
    backgroundColor: 'rgba(22, 101, 52, 0.55)',
    borderColor: 'rgba(74, 222, 128, 0.55)',
  },
  netStatusWarn: {
    backgroundColor: 'rgba(120, 53, 15, 0.55)',
    borderColor: 'rgba(251, 191, 36, 0.55)',
  },
  netStatusFallback: {
    backgroundColor: 'rgba(76, 29, 149, 0.45)',
    borderColor: 'rgba(196, 181, 253, 0.55)',
  },
  netStatusDown: {
    backgroundColor: 'rgba(127, 29, 29, 0.45)',
    borderColor: 'rgba(248, 113, 113, 0.55)',
  },
  netStatusPillText: {
    color: '#F8FAFC',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  netEndpointText: {
    flex: 1,
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '600',
  },
  netBody: {
    gap: 8,
    marginTop: 4,
  },
  netFieldLabel: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  netInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    backgroundColor: '#05080F',
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  netSecureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  netActionRow: {
    flexDirection: 'row',
    gap: 6,
  },
  netConnectBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#0E4A6E',
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.55)',
  },
  netConnectBtnText: {
    color: '#E0F2FE',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textAlign: 'center',
  },
  netDisconnectBtn: {
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#7F1D1D',
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.45)',
  },
  netDisconnectBtnText: {
    color: '#FEE2E2',
    fontSize: 11,
    fontWeight: '800',
  },
  netBtnDisabled: {
    opacity: 0.45,
  },
  netErrorText: {
    color: '#FCA5A5',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  netHint: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 14,
  },
  /** V12.0 — Operator lock / auth */
  headerSecurityRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  roleBadge: {
    flexShrink: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.45)',
    backgroundColor: 'rgba(14, 74, 110, 0.55)',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  roleBadgeText: {
    color: '#E0F2FE',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  lockToggleBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    backgroundColor: '#1E293B',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  lockToggleBtnLocked: {
    borderColor: 'rgba(248, 113, 113, 0.55)',
    backgroundColor: 'rgba(127, 29, 29, 0.45)',
  },
  lockToggleBtnText: {
    color: '#F8FAFC',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  lockOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
    backgroundColor: 'rgba(7, 11, 20, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  lockModal: {
    width: '100%',
    maxWidth: 340,
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(248, 250, 252, 0.18)',
    backgroundColor: 'rgba(15, 23, 42, 0.94)',
    paddingVertical: 22,
    paddingHorizontal: 18,
  },
  lockModalTitle: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 2,
    textAlign: 'center',
  },
  lockModalSubtitle: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    textAlign: 'center',
  },
  lockPinRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    marginVertical: 4,
  },
  lockPinDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.45)',
    backgroundColor: 'transparent',
  },
  lockPinDotFilled: {
    backgroundColor: '#38BDF8',
    borderColor: '#38BDF8',
  },
  lockPinDotError: {
    borderColor: '#F87171',
    backgroundColor: '#F87171',
  },
  lockPinError: {
    color: '#FCA5A5',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
    textAlign: 'center',
  },
  lockKeypad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
  },
  lockKey: {
    width: '30%',
    maxWidth: 88,
    aspectRatio: 1.4,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  lockKeyEmpty: {
    width: '30%',
    maxWidth: 88,
    aspectRatio: 1.4,
  },
  lockKeyText: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '800',
  },
  /** V14.0 — Macro timeline paneli */
  macroCard: {
    gap: 10,
    backgroundColor: '#0C1220',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(244, 114, 182, 0.35)',
    padding: 12,
  },
  macroHint: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '600',
  },
  macroBtnRow: {
    flexDirection: 'row',
    gap: 6,
  },
  macroBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  macroBtnRec: {
    backgroundColor: '#3F1D1D',
    borderColor: 'rgba(248, 113, 113, 0.45)',
  },
  macroBtnRecActive: {
    backgroundColor: '#7F1D1D',
    borderColor: '#F87171',
  },
  macroBtnStop: {
    backgroundColor: '#1E293B',
    borderColor: 'rgba(148, 163, 184, 0.35)',
  },
  macroBtnPlay: {
    backgroundColor: '#14532D',
    borderColor: 'rgba(74, 222, 128, 0.45)',
  },
  macroBtnPlayActive: {
    backgroundColor: '#166534',
    borderColor: '#4ADE80',
  },
  macroBtnText: {
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  macroProgressLabel: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  macroProgressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#0A0F18',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    overflow: 'hidden',
  },
  macroProgressFill: {
    height: '100%',
    backgroundColor: '#64748B',
    borderRadius: 999,
  },
  macroProgressFillActive: {
    backgroundColor: '#4ADE80',
  },
  macroProgressFillRec: {
    backgroundColor: '#F87171',
  },
  macroProgressValue: {
    color: '#CBD5E1',
    fontSize: 11,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },

  /** V15.0 — Diagnostic blackbox terminal */
  diagCard: {
    gap: 8,
    backgroundColor: '#050805',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(74, 222, 128, 0.35)',
    padding: 12,
  },
  diagHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  diagToggle: {
    color: '#4ADE80',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  diagMeta: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '600',
  },
  diagTerminal: {
    backgroundColor: '#000000',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.25)',
    paddingHorizontal: 10,
    paddingVertical: 10,
    minHeight: 160,
    maxHeight: 240,
    gap: 3,
    overflow: 'hidden',
  },
  diagLine: {
    color: '#4ADE80',
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: '600',
    lineHeight: 14,
  },
  diagExportBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#052e16',
    borderWidth: 1,
    borderColor: 'rgba(74, 222, 128, 0.55)',
  },
  diagExportText: {
    color: '#86EFAC',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
  },

  /** V13.0 — Offline queue şeridi */
  offlineQueueRow: {
    gap: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(251, 146, 60, 0.4)',
    backgroundColor: 'rgba(124, 45, 18, 0.28)',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  offlineQueueRowActive: {
    borderColor: 'rgba(251, 191, 36, 0.65)',
    backgroundColor: 'rgba(146, 64, 14, 0.4)',
  },
  offlineQueueText: {
    color: '#FDBA74',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  offlineQueueTextActive: {
    color: '#FDE68A',
  },
  authStatusRow: {
    gap: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.35)',
    backgroundColor: 'rgba(14, 74, 110, 0.28)',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  authStatusRowLocked: {
    borderColor: 'rgba(248, 113, 113, 0.55)',
    backgroundColor: 'rgba(127, 29, 29, 0.35)',
  },
  authStatusText: {
    color: '#BAE6FD',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  authStatusTextLocked: {
    color: '#FECACA',
  },
  controlDisabled: {
    opacity: 0.42,
  },

  /** V11.0 — Art-Net / DMX bridge */
  artnetCard: {
    gap: 8,
    backgroundColor: '#0A101C',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.35)',
    padding: 12,
  },
  artnetSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  artnetSummaryText: {
    flex: 1,
    color: '#FDE68A',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
  },
  artnetBody: {
    gap: 8,
    marginTop: 4,
  },
  artnetUniverseRow: {
    flexDirection: 'row',
    gap: 6,
  },
  artnetUniverseBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#10182A',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
  },
  artnetUniverseBtnActive: {
    backgroundColor: '#78350F',
    borderColor: 'rgba(251, 191, 36, 0.65)',
  },
  artnetUniverseBtnText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '800',
  },
  artnetUniverseBtnTextActive: {
    color: '#FEF3C7',
  },
  artnetUniverseHint: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '600',
  },
  artnetMetaRow: {
    flexDirection: 'row',
    gap: 6,
  },
  artnetMetaBtn: {
    flex: 1,
    gap: 2,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#05080F',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
  },
  artnetMetaValue: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  artnetHexBox: {
    gap: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: '#05080F',
    padding: 10,
  },
  artnetHexText: {
    color: '#FDE68A',
    fontSize: 10,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    lineHeight: 14,
  },
  artnetStatusRow: {
    gap: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.35)',
    backgroundColor: 'rgba(120, 53, 15, 0.28)',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  artnetStatusText: {
    color: '#FDE68A',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
    lineHeight: 16,
  },
    /** V10.0 — PTP clock sync şeridi */
  clockSyncRow: {
    gap: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.35)',
    backgroundColor: 'rgba(6, 78, 59, 0.28)',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  clockSyncRowDrift: {
    borderColor: 'rgba(248, 113, 113, 0.65)',
    backgroundColor: 'rgba(127, 29, 29, 0.4)',
  },
  clockSyncText: {
    color: '#A7F3D0',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
    lineHeight: 16,
  },
  clockSyncTextDrift: {
    color: '#FECACA',
  },
  netLinkRow: {
    gap: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    backgroundColor: '#080D18',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  netLinkLabel: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  netLinkValue: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: '700',
  },
  bpmRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  bpmBtn: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: 88,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10182A',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.16)',
  },
  bpmBtnActive: {
    backgroundColor: '#6D28D9',
    borderColor: 'rgba(196, 181, 253, 0.55)',
  },
  bpmBtnText: {
    color: '#9AA3C2',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  bpmBtnTextActive: {
    color: '#FFFFFF',
  },
  statusPanel: {
    gap: 10,
    backgroundColor: '#0A101C',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.16)',
    padding: 12,
  },
  /** V8.0 — Production telemetry şeridi */
  telemetryStrip: {
    gap: 10,
    backgroundColor: '#05080F',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(250, 250, 250, 0.18)',
    padding: 12,
  },
  telemetryStripIsolated: {
    borderColor: 'rgba(248, 113, 113, 0.65)',
    backgroundColor: 'rgba(69, 10, 10, 0.55)',
  },
  telemetryTitle: {
    color: '#F8FAFC',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.6,
  },
  telemetryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  telemetryCell: {
    flexGrow: 1,
    flexBasis: '45%',
    minWidth: 140,
    gap: 4,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#0A0F18',
    borderWidth: 1,
    borderColor: 'rgba(248, 250, 252, 0.12)',
  },
  telemetryLabel: {
    color: '#94A3B8',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  telemetryValue: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.4,
  },
  telemetryValueAccent: {
    color: '#4ADE80',
  },
  telemetryValueWarn: {
    color: '#C4B5FD',
  },
  telemetryValueDanger: {
    color: '#FCA5A5',
  },
  telemetryIsolatedBox: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.45)',
    backgroundColor: 'rgba(127, 29, 29, 0.35)',
  },
  telemetryIsolatedText: {
    color: '#FECACA',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 2,
  },
  telemetryIsolatedHint: {
    color: '#FCA5A5',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  logBox: {
    gap: 6,
    backgroundColor: '#080D18',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.12)',
    paddingVertical: 10,
    paddingHorizontal: 10,
    minHeight: 88,
  },
  logBoxTitle: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  logLine: {
    color: '#CBD5E1',
    fontSize: 12,
    fontWeight: '500',
    fontVariant: ['tabular-nums'],
  },
  logEmpty: {
    color: '#64748B',
    fontSize: 12,
    fontStyle: 'italic',
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  moduleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#10182A',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.28)',
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  moduleBadgeLabel: {
    color: '#E2E8F0',
    fontSize: 11,
    fontWeight: '600',
  },
  moduleBadgeOk: {
    color: '#34D399',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  payloadMonitor: {
    gap: 8,
  },
  payloadBox: {
    backgroundColor: '#05080F',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.28)',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  payloadCode: {
    color: '#7DD3FC',
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'monospace',
    fontVariant: ['tabular-nums'],
  },
  ackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: '#0A101C',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  ackRowOk: {
    borderColor: 'rgba(52, 211, 153, 0.55)',
    backgroundColor: 'rgba(6, 78, 59, 0.35)',
  },
  ackRowPending: {
    borderColor: 'rgba(251, 191, 36, 0.45)',
    backgroundColor: 'rgba(69, 26, 3, 0.28)',
  },
  ackRowFailed: {
    borderColor: 'rgba(248, 113, 113, 0.5)',
    backgroundColor: 'rgba(127, 29, 29, 0.3)',
  },
  ackDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#64748B',
  },
  ackDotOk: {
    backgroundColor: '#34D399',
  },
  ackDotPending: {
    backgroundColor: '#FBBF24',
  },
  ackDotFailed: {
    backgroundColor: '#F87171',
  },
  ackText: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  ackTextOk: {
    color: '#6EE7B7',
  },
  ackTextPending: {
    color: '#FCD34D',
  },
  ackTextFailed: {
    color: '#FCA5A5',
  },
  socketBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  socketBadgeOnline: {
    borderColor: 'rgba(52, 211, 153, 0.45)',
  },
  socketBadgeReconnect: {
    borderColor: 'rgba(251, 191, 36, 0.45)',
  },
  socketBadgeFallback: {
    borderColor: 'rgba(196, 181, 253, 0.55)',
  },
  socketBadgeOffline: {
    borderColor: 'rgba(248, 113, 113, 0.5)',
  },
  socketDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#64748B',
  },
  socketDotOnline: {
    backgroundColor: '#34D399',
  },
  socketDotReconnect: {
    backgroundColor: '#FBBF24',
  },
  socketDotFallback: {
    backgroundColor: '#C4B5FD',
  },
  socketDotOffline: {
    backgroundColor: '#F87171',
  },
  socketText: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  socketTextOnline: {
    color: '#6EE7B7',
  },
  socketTextFallback: {
    color: '#DDD6FE',
  },
  socketTextOffline: {
    color: '#FCA5A5',
  },
  hardwareRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  hardwareBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    backgroundColor: '#080D18',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  hardwareBadgeOk: {
    borderColor: 'rgba(52, 211, 153, 0.4)',
  },
  hardwareBadgeWarn: {
    borderColor: 'rgba(251, 191, 36, 0.4)',
  },
  hardwareBadgePulse: {
    borderColor: 'rgba(52, 211, 153, 0.7)',
    backgroundColor: 'rgba(6, 78, 59, 0.35)',
  },
  hardwareDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#64748B',
  },
  hardwareDotOk: {
    backgroundColor: '#34D399',
  },
  hardwareDotWarn: {
    backgroundColor: '#FBBF24',
  },
  hardwareText: {
    color: '#E2E8F0',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  audioListenBtn: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.35)',
    backgroundColor: '#10182A',
    paddingVertical: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  audioListenBtnActive: {
    borderColor: 'rgba(52, 211, 153, 0.65)',
    backgroundColor: 'rgba(6, 78, 59, 0.4)',
  },
  audioListenBtnText: {
    color: '#7DD3FC',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  audioListenBtnTextActive: {
    color: '#6EE7B7',
  },
  autoBpmHint: {
    gap: 6,
    marginTop: 2,
  },
  autoBpmHintText: {
    color: '#34D399',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  audioSyncCard: {
    gap: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.16)',
    backgroundColor: '#080D18',
    padding: 10,
  },
  audioSyncCardActive: {
    borderColor: 'rgba(52, 211, 153, 0.45)',
  },
  audioSyncLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  audioSyncLabelOn: {
    color: '#34D399',
  },
  micLevelLabel: {
    color: '#9AA3C2',
    fontSize: 10,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  micBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.15)',
    overflow: 'hidden',
  },
  micBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#22D3EE',
  },
});
