name: Deploy to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH ile Sunucuya Baglan ve Guncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 178.104.139.203
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            systemctl stop nginx || true
            systemctl disable nginx || true
            pkill -9 nginx || true
            cd /root/pulse-app
            git pull origin main
            docker compose down || true
            docker compose up -d --build
